on: [ push, pull_request ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create coverage reports
        run: go test -coverprofile=coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: golang-module/base64Captcha
